[dns_provider]
email_env_var = "CF_EMAIL"
api_key_env_var = "CF_API_KEY"
zone_id_env_var = "CF_ZONE_ID"
dns_record_id_env_var = "CF_DNS_RECORD_ID"
dns_record_name = "_dnslink.reimagined-palm-tree.lrad.io"

[ipfs_api_server]
host = "localhost"
port = 5001
